"""alter_issued_by_received_by_to_string

Revision ID: a1b2c3d4e5f6
Revises: 3755e0d7220f
Create Date: 2026-07-21 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '3755e0d7220f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('borrow_transactions_ibfk_2', 'borrow_transactions', type_='foreignkey')
    op.drop_constraint('returns_ibfk_2', 'returns', type_='foreignkey')
    op.alter_column('borrow_transactions', 'issued_by',
               existing_type=sa.BigInteger(),
               type_=sa.String(100),
               existing_nullable=False)
    op.alter_column('returns', 'received_by',
               existing_type=sa.BigInteger(),
               type_=sa.String(100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('returns', 'received_by',
               existing_type=sa.String(100),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('borrow_transactions', 'issued_by',
               existing_type=sa.String(100),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_foreign_key('returns_ibfk_2', 'returns', 'users', ['received_by'], ['id'])
    op.create_foreign_key('borrow_transactions_ibfk_2', 'borrow_transactions', 'users', ['issued_by'], ['id'])
    # ### end Alembic commands ###
